/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as FantmsRouteImport } from './routes/fantms'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiTelegramRouteImport } from './routes/api.telegram'
import { Route as GroupsIdRouteImport } from './routes/groups.$id'
import { Route as SplitCodeRouteImport } from './routes/split.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPushTickRouteImport } from './routes/api.push.tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const FantmsRoute = FantmsRouteImport.update({
  id: '/fantms',
  path: '/fantms',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GroupsRoute,
} as any)
const SplitCodeRoute = SplitCodeRouteImport.update({
  id: '/split/$code',
  path: '/split/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushTickRoute = ApiPushTickRouteImport.update({
  id: '/api/push/tick',
  path: '/api/push/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/bills': typeof BillsRoute
  '/fantms': typeof FantmsRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/receipts': typeof ReceiptsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/groups/$id': typeof GroupsIdRoute
  '/split/$code': typeof SplitCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/tick': typeof ApiPushTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/bills': typeof BillsRoute
  '/fantms': typeof FantmsRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/receipts': typeof ReceiptsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/groups/$id': typeof GroupsIdRoute
  '/split/$code': typeof SplitCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/tick': typeof ApiPushTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/bills': typeof BillsRoute
  '/fantms': typeof FantmsRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/receipts': typeof ReceiptsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/groups/$id': typeof GroupsIdRoute
  '/split/$code': typeof SplitCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/tick': typeof ApiPushTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/bills'
    | '/fantms'
    | '/groups'
    | '/login'
    | '/receipts'
    | '/scan'
    | '/settings'
    | '/api/telegram'
    | '/groups/$id'
    | '/split/$code'
    | '/api/auth/$'
    | '/api/push/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent'
    | '/bills'
    | '/fantms'
    | '/groups'
    | '/login'
    | '/receipts'
    | '/scan'
    | '/settings'
    | '/api/telegram'
    | '/groups/$id'
    | '/split/$code'
    | '/api/auth/$'
    | '/api/push/tick'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/bills'
    | '/fantms'
    | '/groups'
    | '/login'
    | '/receipts'
    | '/scan'
    | '/settings'
    | '/api/telegram'
    | '/groups/$id'
    | '/split/$code'
    | '/api/auth/$'
    | '/api/push/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  BillsRoute: typeof BillsRoute
  FantmsRoute: typeof FantmsRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  SplitCodeRoute: typeof SplitCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPushTickRoute: typeof ApiPushTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantms': {
      id: '/fantms'
      path: '/fantms'
      fullPath: '/fantms'
      preLoaderRoute: typeof FantmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/split/$code': {
      id: '/split/$code'
      path: '/split/$code'
      fullPath: '/split/$code'
      preLoaderRoute: typeof SplitCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/tick': {
      id: '/api/push/tick'
      path: '/api/push/tick'
      fullPath: '/api/push/tick'
      preLoaderRoute: typeof ApiPushTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GroupsRouteChildren {
  GroupsIdRoute: typeof GroupsIdRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsIdRoute: GroupsIdRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  BillsRoute: BillsRoute,
  FantmsRoute: FantmsRoute,
  GroupsRoute: GroupsRouteWithChildren,
  LoginRoute: LoginRoute,
  ReceiptsRoute: ReceiptsRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  SplitCodeRoute: SplitCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPushTickRoute: ApiPushTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
